name: Tower Launch Hello World
# The Hello World pipeline will be launched on all Compute Environments in the Tower Workspace.
# This workflow can be triggered manually with the GitHub actions workflow dispatch button.

on:
  workflow_dispatch:
jobs:
  tw-launch-hello-world:
    name: Tower Launch Hello World
    if: github.repository == 'seqeralabs/showcase'
    runs-on: ubuntu-latest
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
      TOWER_WORKSPACE_NAME: seqeralabs/showcase
    steps:
      - name: Install tw CLI
        run: |
          wget -L https://github.com/seqeralabs/tower-cli/releases/download/v0.7.3/tw-0.7.3-linux-x86_64
          mv tw-* tw
          chmod +x tw
          sudo mv tw /usr/local/bin/

      - name: Tower Launch Hello World
        run: |
          # Get list of Compute Environments in Workspace
          COMPUTE_ENVS=( $( tw -o json compute-envs list --workspace=$TOWER_WORKSPACE_NAME | jq -r '.computeEnvs[].name' ) )
          
          # Loop through Compute Environments
          for i in "${!COMPUTE_ENVS[@]}"
          do 
            WORK_DIR=( $( tw compute-envs export --name=${COMPUTE_ENVS[$i]} --workspace=$TOWER_WORKSPACE_NAME | jq -r '.workDir' ) )
            
            # Tower Launch Hello World
            tw launch --workspace=$TOWER_WORKSPACE_NAME --compute-env=${COMPUTE_ENVS[$i]} --name="HOLA_${COMPUTE_ENVS[$i]}" --work-dir=$WORK_DIR hello
          done
