name: Tower Launch Hello World
# The Hello World pipeline will be launched on a specified set of Compute Environments in a Tower Workspace.
# This workflow can be triggered manually with the GitHub actions workflow dispatch button.

on:
  workflow_dispatch:
jobs:
  tw-launch-hello-world:
    name: Tower Launch Hello World
    if: github.repository == 'seqeralabs/showcase'
    runs-on: ubuntu-latest
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
      TOWER_WORKSPACE_NAME: seqeralabs/showcase
    strategy:
      matrix:
        compute-env: [ 'seqera_aws_ireland_fusionv2_nvme', 'seqera_azure_virginia', 'seqera_gcp_london' ]
        include:
          - compute-env: "seqera_aws_ireland_fusionv2_nvme"
            run-name: "Hola_AWS_Ireland"
          - compute-env: "seqera_azure_virginia"
            run-name: "Hola_Azure_Virginia"
          - compute-env: "seqera_gcp_london"
            run-name: "Hola_GCP_London"
    steps:
      - name: Install tw CLI
        run: |
          wget -L https://github.com/seqeralabs/tower-cli/releases/download/v0.7.3/tw-0.7.3-linux-x86_64
          mv tw-* tw
          chmod +x tw
          sudo mv tw /usr/local/bin/

      - name: Tower Launch Hello World
        run: |
          WORK_DIR=( $( tw compute-envs export --name=${{ matrix.compute-env }} --workspace=$TOWER_WORKSPACE_NAME | jq -r '.workDir' ) )
            
          # Tower Launch Hello World
          tw launch --workspace=$TOWER_WORKSPACE_NAME --compute-env=${{ matrix.compute-env }} --name=${{ matrix.run-name }} --work-dir=$WORK_DIR hello
